services:
  # A Docker web service
  - type: web
    name: invoiceapi
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: fastapi run app/main.py
